apiVersion: v1
kind: Service
metadata:
  name: sample-demo
  labels:
    app: sample-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sample-demo
    tier: sample-demo
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-demo
  labels:
    app: sample-demo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample-demo
        tier: sample-demo
    spec:
      containers:
      - image: sample-demo:latest
        name: sample-demo
        ports:
        - containerPort: 8080
          name: sample-demo